#base image, alpine means minimal 
FROM node:alpine
WORKDIR /usr/app

#install some dependencies, copy irl directory to docker directory
COPY ./package.json ./  
RUN npm install
COPY ./ ./

#default command
CMD ["npm", "start"]